#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
apt-get -y update
apt-get -y install haproxy

# Configure HAProxy
server_config='
frontend  mqnifestkelvin_frontend
    bind *:80
    mode http
    default_backend mqnifestkelvin_backend

backend mqnifestkelvin_backend
    balance roundrobin
    server 111919-web-01 72.44.62.244:80 check
    server 111919-web-02 54.210.123.54:80 check
'

echo "$server_config" >> /etc/haproxy/haproxy.cfg

# Enable HAProxy to be managed via an init script
echo "ENABLED=1" >> /etc/default/haproxy

# Testing the HAProxy configuration file
haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
systemctl restart haproxy