#!/usr/bin/env bash
# printing numbers from 1 to 20
# printing "bad luck from China" after 4
# printing "bad luck from Japan" after 9
# printing "bad luck from Italy" after 17

i=0
while [ $i -le 20 ]
do
	echo "$i"
	if [ $i -eq 3 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 8 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 16 ]
	then
		echo "bad luck from Italy"
	fi
	i=$((i+1))
done
