#!/usr/bin/env bash
# printing numbers from 1 to 20
# printing "bad luck from China" after 4
# printing "bad luck from Japan" after 9
# printing "bad luck from Italy" after 17

i=0

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from Italy";;
	esac
	i=$((i+1))
done
